### ISSUE TITLE
Prepopulate "Add Deployment" page with query parameters

### ISSUE THREAD

**Issue by dan-kirberger** [go-vela/community#408] opened 2021-10-13 18:14 UTC
## Description

Right now you can go to the "Create Deployment" page in Vela to request a new deployment:
![image](https://user-images.githubusercontent.com/16195927/137189107-d8faba99-674b-49af-955f-6e879d9444cd.png)

It would be slick if we could help auto-populate those fields, perhaps visiting a link like this:

https://vela.prod.target.com/MY_ORG/MY_REPO/add-deployment?target=prod&ref=v1.2.3&etc...

This would still load the form (NOT submit it automatically), but would pre-populate the relevant fields.

## Value

We have tooling (and slack messages) that could generate these links for engineers to use to simplify promoting code to higher environments.

Perhaps after a build completes in the main branch, we send this message to slack "to promote this to prod, use <link here>".

Personally, for my team we aren't using deployments yet, but I'd like to (as a way to standardize how we deploy), this would help simplify wrangling those releases.

**Comment by cognifloyd** [comment] 2022-05-20 17:37
This is a duplicate of #451

**Closed by cognifloyd** 2022-05-20 17:37 UTC
Labels: enhancement, good first issue, area/ui

**Comment by dan-kirberger** [comment] 2022-05-20 17:40
Ha, both made by me, less than two months apart. 🤷
