### ISSUE TITLE
Log Ref in "No valid template found" Error

### ISSUE THREAD

**Issue by newlandk** [go-vela/community#174] opened 2020-12-28 15:55 UTC
## Description

Make it more clear to the user when Vela fails to collect a template file, log the ref to specify which branch Vela attempted to collect.

## Value

When setting up a template it can be difficult to understand where Vela is trying to collect the template file from (master vs. main). This could be especially helpful if a branch name changes or an explicit branch was specified and a template collection fails. This will give the user additional context to why the template failed to be collected in the log.

## Definition of Done

I believe the extent of the change would be to log `s.Ref` here: 

https://github.com/go-vela/compiler/blob/adf85cc6f434c069476eb3401cb9d9c1ea854585/registry/github/template.go#L51

## Effort  (Optional)

5 Minutes

**Comment by susangreve** [comment] 2021-05-19 14:48
Closing this issue as a dupe of #221

**Closed by susangreve** 2021-05-19 14:48 UTC
Labels: enhancement
