### ISSUE TITLE
"Finished" time for an ongoing build shows past date

### ISSUE THREAD

**Issue by keshav2211** [go-vela/community#259] opened 2021-05-04 15:11 UTC
## "Finished" time for an ongoing build shows past date - January 1st, 1970

* What are the results you received?
"Finished" time for ongoing build is shown January 1st, 1970 on UI
* What are the results you expected?
 It should ideally not show any date until build is complete
* Can you provide the steps to reproduce it?
 Trigger a build, go to recent builds, hover on the on-going build
* Can you provide links or code snippets?
No

## Value

* Why is this important?
It makes sense to not show a past date for on-going build
* Does this have an impact on security?
No

## Useful Information

1. What is the output of `vela --version`?

v0.7.4
2. What operating system is being used?

macOs Catalina

3. Any other important details?

screenshot attached
<img width="329" alt="vela_finish_time" src="https://user-images.githubusercontent.com/8353822/117024284-78f35c80-ad17-11eb-862a-aed1e17032a2.png">

**Comment by wass3r** [comment] 2021-05-04 18:52
dupe of https://github.com/go-vela/community/issues/244 - fix will be in the next release.

**Closed by wass3r** 2021-05-04 18:52 UTC
Labels: bug
