### ISSUE TITLE
Fix logs are getting truncated

### ISSUE THREAD

**Issue by kneal** [go-vela/community#128] opened 2020-10-07 20:19 UTC
## Description

Users have observed that the last message outputted in a step sometimes gets truncated and is not shipped to the server.

## Value

The full log is available to users within the server

## Useful Information

Example pipeline that can be used to test behavior:

```
version: "1"

steps:
  - name: view message
    image: alpine:latest
    pull: always
    commands:
      - "[ -s /vela/secrets/hello ] || echo \"file is empty\""
      - cat /vela/secrets/hello
      - sleep 2
              
secrets:
  - name: vault_username
  - name: vault_password
  - origin:
      name: vault secrets
      image: target/vela/secret-vault:latest
      pull: always
      secrets: [ vault_username, vault_password ]
      parameters:
        log_level: trace
        items:
          - source: secret/vela/hello
            path: single
```

**Comment by jbrockopp** [comment] 2020-10-29 18:03
I began exploring this today 👍 

First, I'll provide some links to resources that are worth mentioning in the context of this issue:

* https://github.com/moby/moby/issues/31058
* https://stackoverflow.com/questions/40389137/multiple-docker-container-logs
* https://jaxenter.com/docker-logging-gotchas-137049.html

I approached it how I normally approach bugs by reproducing it first on my local workstation.

The pipeline I used to reproduce this issue is the same as what was provided in the initial message of this issue. The only caveat is that I had to comment out the line containing `- sleep 2` otherwise I always saw the log content render properly.

```yaml
version: "1"

steps:
  - name: view message
    image: alpine:latest
    pull: always
    commands:
      - "[ -s /vela/secrets/hello ] || echo \"file is empty\""
      - cat /vela/secrets/hello
    # I had to remove this line because the output from the above `cat` command was always displaying
    # - sleep 2 
              
secrets:
  - name: vault_username
  - name: vault_password

  - origin:
      name: vault secrets
      image: target/vela/secret-vault:latest
      pull: always
      secrets: [ vault_username, vault_password ]
      parameters:
        log_level: trace
        items:
          - source: secret/vela/hello
            path: single
```

**Comment by jbrockopp** [comment] 2020-10-29 18:16
After reproducing the bug, I commented out the code responsible on the worker for cleaning up build resources:

* [Lines to be commented out](https://github.com/go-vela/worker/blob/master/cmd/vela-worker/exec.go#L105-L112)
* [Lines to be commented out](https://github.com/go-vela/worker/blob/master/cmd/vela-worker/exec.go#L146-L151)

The goal of this is to prevent the container for the step `view message` from being removed on my local workstation.

This will allow me to manually inspect the content of the logs recorded by Docker to see if there is a mismatch.

After doing this, I found that their was a mismatch between what we recorded and what was recorded by Docker:

```bash
$ docker logs b87e73fa993b

$ [ -s /vela/secrets/single/message ] || echo "file is empty"
$ cat /vela/secrets/single/message
hello_world%
```

**Comment by jbrockopp** [comment] 2020-10-29 18:51
To verify the issue is in the code, we'll need to troubleshoot where we first capture log content from the container.

I've [created a branch](https://github.com/go-vela/pkg-runtime/compare/fix/docker/missing_logs) that attempts to directly output to stdout [the contents from the API call](https://github.com/go-vela/pkg-runtime/blob/968531760fad17e4c08a8aa9eddddec42fec383e/runtime/docker/container.go#L215-L226) sent to the Docker daemon:

```go
	// send API call to capture the container logs
	//
	// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
	logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
	if err != nil {
		return nil, err
	}

	_, err = io.Copy(os.Stdout, logs)
	if err != nil {
		return nil, err
	}
```

Unfortunately, I was unsuccessful in being able to view the last line of the logs using this method.

This **could indicate** the issue is in the underlying Docker client/library we're using to send API calls to the daemon.

This **could equally indicate** the issue is in the method I'm using (`io.Copy`) to capture the content.

At this point, I'm leaning towards it being the latter because previously we would intermittently not see the final log line.

Now, with this new code, I'm seeing it consistently miss that last log line.

Further methods of attempting to capturing content from the API call will be required.

**Comment by jbrockopp** [comment] 2020-10-29 19:12
Before using a different method, I decided to experiment and see if timing plays a factor into the behavior experienced.

I've updated the branch to include [a sleep statement of `1` second](https://github.com/go-vela/pkg-runtime/blob/a1bcda11ac810804d871fa044b38d77b45f02053/runtime/docker/container.go#L216-L235) before copying the container logs to stdout:

```go
	// send API call to capture the container logs
	//
	// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
	logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
	if err != nil {
		return nil, err
	}

	// <-------------------- Testing -------------------->

	// sleep for 1 second
	time.Sleep(1 * time.Second)

	// directly copy container logs to stdout
	_, err = io.Copy(os.Stdout, logs)
	if err != nil {
		return nil, err
	}

	// <---------------- End Of Testing ---------------->
```

Unfortunately, this was also unsuccessful, like the last method, in being able to view the last line of the logs.

At this point, I'm drawing the same conclusions and will begin testing new methods of outputting the logs to stdout.

**Comment by jbrockopp** [comment] 2020-10-29 19:32
The new method I'm testing to directly output the container logs to stdout is using [Docker's stdcopy package](https://godoc.org/github.com/docker/docker/pkg/stdcopy).

I've updated the branch to now [switch from `io.Copy` to `stdcopy.Stdcopy`](https://github.com/go-vela/pkg-runtime/commit/afdd0045b106c285824f0b3592f6598d63deb999) for copying the container logs to stdout:

```go
	// send API call to capture the container logs
	//
	// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
	logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
	if err != nil {
		return nil, err
	}

	// <-------------------- Testing -------------------->

	// directly copy container stdout and stderr logs to stdout
	//
	// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
	_, err = stdcopy.StdCopy(os.Stdout, os.Stdout, logs)
	if err != nil {
		return nil, err
	}

	// <---------------- End Of Testing ---------------->
```

Unfortunately, this was also unsuccessful, like the last method, in being able to view the last line of the logs.

**Comment by jbrockopp** [comment] 2020-10-29 19:44
After viewing [the `stdcopy.StdCopy` function](https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy) more closely, it appears it accepts stdout and stderr as arguments.

I've updated the branch to now [use `stdcopy.StdCopy` with both stdout and stderr](https://github.com/go-vela/pkg-runtime/blob/f66fc528bac1dad9e4e709cfcd99efbfa50d1499/runtime/docker/container.go#L215-L233):

```go
	// send API call to capture the container logs
	//
	// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
	logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
	if err != nil {
		return nil, err
	}

	// <-------------------- Testing -------------------->

	// directly copy container stdout and stderr logs to OS stdout and stderr
	//
	// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
	_, err = stdcopy.StdCopy(os.Stdout, os.Stderr, logs)
	if err != nil {
		return nil, err
	}

	// <---------------- End Of Testing ---------------->
```

Unfortunately, this was also unsuccessful, like the last method, in being able to view the last line of the logs.

**Comment by jbrockopp** [comment] 2020-10-29 20:21
Before making any changes again, I decided to experiment and see if timing plays a factor into the behavior experienced.

I've updated the branch to include [a sleep statement of `1` second](https://github.com/go-vela/pkg-runtime/blob/2a3d7547652fd76c33dbb8e140a51399aeb393ad/runtime/docker/container.go#L216-L237) before copying the container logs:

```go
	// send API call to capture the container logs
	//
	// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
	logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
	if err != nil {
		return nil, err
	}

	// <-------------------- Testing -------------------->

	// sleep for 1 second
	time.Sleep(1 * time.Second)

	// directly copy container stdout and stderr logs to OS stdout and stderr
	//
	// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
	_, err = stdcopy.StdCopy(os.Stdout, os.Stderr, logs)
	if err != nil {
		return nil, err
	}

	// <---------------- End Of Testing ---------------->
```

Unfortunately, this was also unsuccessful, like the last method, in being able to view the last line of the logs.

At this point, I'm drawing the same conclusions and will begin testing new methods of outputting the logs.

**Comment by jbrockopp** [comment] 2020-10-30 16:26
The new method I'm testing to directly output the container logs to stdout will continue to use [Docker's stdcopy package](https://godoc.org/github.com/docker/docker/pkg/stdcopy).

However, I've updated the branch to now [copy contents from the API call](https://github.com/go-vela/pkg-runtime/blob/f345ae01f69ca346a405728ad9ac491c17e2dc24/runtime/docker/container.go#L228-L252) to the Docker daemon in a go routine:

```go
	// capture all stdout and stderr logs
	go func() {
		// defer closing all buffers
		defer func() {
			// close logs buffer
			logs.Close()


			// close in-memory pipe write closer
			wc.Close()


			// close in-memory pipe read closer
			rc.Close()
		}()


		// <-------------------- Testing -------------------->


		// directly copy container stdout and stderr logs to OS stdout and stderr
		//
		// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
		_, err = stdcopy.StdCopy(os.Stdout, os.Stderr, logs)
		if err != nil {
			logrus.Errorf("unable to copy logs for container: %v", err)
		}


		// <---------------- End Of Testing ---------------->
```

Unfortunately, this was also unsuccessful, like the last method, in being able to view the last line of the logs.

**Comment by jbrockopp** [comment] 2020-10-30 16:44
Before making any changes again, I decided to experiment and see if timing plays a factor into the behavior experienced.

I've updated the branch to include [a sleep statement of `1` second](https://github.com/go-vela/pkg-runtime/blob/eab1c85899101e5abfd145d454f8f35aef3f62a3/runtime/docker/container.go#L229-L256) before copying the container logs:

```go
	// capture all stdout and stderr logs
	go func() {
		// defer closing all buffers
		defer func() {
			// close logs buffer
			logs.Close()

			// close in-memory pipe write closer
			wc.Close()

			// close in-memory pipe read closer
			rc.Close()
		}()

		// <-------------------- Testing -------------------->

		// sleep for 1 second
		time.Sleep(1 * time.Second)

		// directly copy container stdout and stderr logs to OS stdout and stderr
		//
		// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
		_, err = stdcopy.StdCopy(os.Stdout, os.Stderr, logs)
		if err != nil {
			logrus.Errorf("unable to copy logs for container: %v", err)
		}

		// <---------------- End Of Testing ---------------->
```

Unfortunately, this was also unsuccessful, like the last method, in being able to view the last line of the logs.

**Comment by jbrockopp** [comment] 2020-11-02 13:29
The new method I'm testing to directly output the container logs to stdout will continue to use [Docker's stdcopy package](https://godoc.org/github.com/docker/docker/pkg/stdcopy).

However, I've updated the branch [make the API call to capture the logs](https://github.com/go-vela/pkg-runtime/blob/f65860be7ee11f41bb5478ec494f96d0fee59527/runtime/docker/container.go#L228-L260) from the Docker daemon in a go routine:

```go
	// capture all stdout and stderr logs
	go func() {
		// defer closing all buffers
		defer func() {
			// close logs buffer
			logs.Close()

			// close in-memory pipe write closer
			wc.Close()

			// close in-memory pipe read closer
			rc.Close()
		}()

		// <-------------------- Testing -------------------->

		// send API call to capture the container logs
		//
		// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
		logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
		if err != nil {
			logrus.Errorf("unable to capture logs for container: %v", err)
		}

		// directly copy container stdout and stderr logs to OS stdout and stderr
		//
		// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
		_, err = stdcopy.StdCopy(os.Stdout, os.Stderr, logs)
		if err != nil {
			logrus.Errorf("unable to copy logs for container: %v", err)
		}

		// <---------------- End Of Testing ---------------->
```

Unfortunately, this was also unsuccessful, like the last method, in being able to view the last line of the logs.

**Comment by jbrockopp** [comment] 2020-11-02 15:02
Before testing a new method again, I decided to play around with some of the buffer closures.

I've updated the branch to [move the `logs` buffer closure](https://github.com/go-vela/pkg-runtime/blob/06196883efb1dc8d6fb6299bcb31f06586ff8ac1/runtime/docker/container.go#L206-L248) till after we complete copying the container logs:

```go
	// capture all stdout and stderr logs
	go func() {
		// defer closing all buffers
		defer func() {
			// close in-memory pipe write closer
			wc.Close()

			// close in-memory pipe read closer
			rc.Close()
		}()

		// create options for capturing container logs
		//
		// https://godoc.org/github.com/docker/docker/api/types#ContainerLogsOptions
		opts := types.ContainerLogsOptions{
			Follow:     true,
			ShowStdout: true,
			ShowStderr: true,
			Details:    false,
			Timestamps: false,
		}

		// send API call to capture the container logs
		//
		// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
		logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
		if err != nil {
			logrus.Errorf("unable to capture logs for container: %v", err)
		}

		logrus.Tracef("copying logs for container %s", ctn.ID)

		// copy container stdout and stderr logs to our in-memory pipe
		//
		// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
		_, err = stdcopy.StdCopy(wc, wc, logs)
		if err != nil {
			logrus.Errorf("unable to copy logs for container: %v", err)
		}

		// close logs buffer
		logs.Close()
	}()
```

This seemed to slightly increase the chances of getting the full output from the container 👍 

However, that increase was very minimal as I'm still seeing the logs missing ~ 50% of the time.

**Comment by jbrockopp** [comment] 2020-11-02 15:33
Before testing a new method again, I decided to continue messing with the buffer closures.

I've updated the branch to [remove the `defer` for buffer closures](https://github.com/go-vela/pkg-runtime/blob/65778c7403191664a139369b62515f9ccb0e3449/runtime/docker/container.go#L206-L242) till after we complete copying the container logs:

```go
	// capture all stdout and stderr logs
	go func() {
		// create options for capturing container logs
		//
		// https://godoc.org/github.com/docker/docker/api/types#ContainerLogsOptions
		opts := types.ContainerLogsOptions{
			Follow:     true,
			ShowStdout: true,
			ShowStderr: true,
			Details:    false,
			Timestamps: false,
		}

		// send API call to capture the container logs
		//
		// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
		logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
		if err != nil {
			logrus.Errorf("unable to tail output for container: %v", err)
		}

		logrus.Tracef("copying logs for container %s", ctn.ID)

		// copy container stdout and stderr logs to our in-memory pipe
		//
		// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
		_, err = stdcopy.StdCopy(wc, wc, logs)
		if err != nil {
			logrus.Errorf("unable to copy logs for container: %v", err)
		}

		// close logs buffer
		logs.Close()

		// close in-memory pipe write closer
		wc.Close()
	}()
```

This didn't really seem to offer a notable difference in the content rendered for the logs.

We're still seeing the logs missing ~ `50%` of the time.

**Comment by jbrockopp** [comment] 2020-11-02 16:13
Before testing a new method again, I decided to experiment and see if timing plays a factor into the behavior experienced.

I've updated the branch to include [a sleep statement of `1` second](https://github.com/go-vela/pkg-runtime/blob/96fa5305916aac7ec51eb22f0e45d0415ee0838b/runtime/docker/container.go#L207-L246) before capturing the container logs:

```go
	// capture all stdout and stderr logs
	go func() {
		// sleep for 1 second
		time.Sleep(1 * time.Second)

		// create options for capturing container logs
		//
		// https://godoc.org/github.com/docker/docker/api/types#ContainerLogsOptions
		opts := types.ContainerLogsOptions{
			Follow:     true,
			ShowStdout: true,
			ShowStderr: true,
			Details:    false,
			Timestamps: false,
		}

		// send API call to capture the container logs
		//
		// https://godoc.org/github.com/docker/docker/client#Client.ContainerLogs
		logs, err := c.docker.ContainerLogs(ctx, ctn.ID, opts)
		if err != nil {
			logrus.Errorf("unable to tail output for container: %v", err)
		}

		logrus.Tracef("copying logs for container %s", ctn.ID)

		// copy container stdout and stderr logs to our in-memory pipe
		//
		// https://godoc.org/github.com/docker/docker/pkg/stdcopy#StdCopy
		_, err = stdcopy.StdCopy(wc, wc, logs)
		if err != nil {
			logrus.Errorf("unable to copy logs for container: %v", err)
		}

		// close logs buffer
		logs.Close()

		// close in-memory pipe write closer
		wc.Close()
	}()
```

Unfortunately, this was also unsuccessful in being able to view the last line of the logs.

**Comment by jbrockopp** [comment] 2020-11-02 16:57
Before testing a new method again, I decided to experiment with upgrading the [docker/docker](https://github.com/docker/docker) library.

I've updated the branch to [upgrade the `docker/docker` dependency](https://github.com/go-vela/pkg-runtime/blob/66ff1098ee6192cc603f776eb7c98219f2dad448/go.mod#L8) in the go module:

```diff
-	github.com/docker/docker v0.7.3-0.20190327010347-be7ac8be2ae0
+	github.com/docker/docker v1.4.2-0.20200309214505-aa6a9891b09c
```

This didn't really seem to offer a notable difference in the content rendered for the logs.

I'm still seeing the logs missing ~ `50%` of the time.

**Comment by jbrockopp** [comment] 2020-11-02 17:12
Before testing a new method again, I decided to experiment with the version of the Docker API we pin to.

I've updated the branch to [upgrade the Docker API version to `1.40`](https://github.com/go-vela/pkg-runtime/blob/28c1adf6fa209035fac5809f767c0f204f97c0f3/runtime/docker/docker.go#L15-L16):

```diff
// expected version for the Docker API
- const version = "1.38"
+ const version = "1.40"
```

This didn't really seem to offer a notable difference in the content rendered for the logs.

I'm still seeing the logs missing ~ `50%` of the time.

**Comment by jbrockopp** [comment] 2020-11-06 17:47
After some pretty exhaustive testing, I decided to see if I could replicate the behavior using native Docker measures.

To replicate this, I essentially would run a build locally, and in a terminal window have the following running:

```bash
watch -n 1 docker logs -f <container_id>
```

The end result experienced was **the exact same** as what we were seeing from a code perspective.

In short, ~ `50%` of the time, I would see:

```
1 | $ [ -s /vela/secrets/hello ] \|\| echo "file is empty"
2 | $ cat /vela/secrets/hello
3 |  
```
And the other ~ `50%` of the time, I would see:

```
1 | $ [ -s /vela/secrets/hello ] \|\| echo "file is empty"
2 | $ cat /vela/secrets/hello
3 | hello_world
```

This indicates that we'll need to explore a different method of capturing all logs from the container for final upload 👍

**Comment by jbrockopp** [comment] 2020-11-06 17:50
I've opened https://github.com/go-vela/pkg-runtime/pull/64 to address **part of the issue** we see from streaming logs.

On the worker, we've seen log messages to the effect of:

```
io: read/write on closed pipe
```

In that PR you'll find more details explaining how it fixes this issue 👍 

The tl;dr is we were closing the read buffer for the container before all logs had been uploaded to Vela.

**Comment by jbrockopp** [comment] 2020-11-11 17:17
I've opened https://github.com/go-vela/pkg-executor/pull/64 to address **part of the issue** we see from streaming logs.

In that PR you'll find more details explaining how it fixes this issue 👍

The tl;dr is we now make an extra runtime call to tail the step logs **AFTER** the container completes.

This should guarantee no logs are missing when we upload the final logs to the server.

**Comment by jbrockopp** [comment] 2020-11-16 17:14
I've opened https://github.com/go-vela/worker/pull/125 which should close this issue 👍 

It vendors in the new code from https://github.com/go-vela/pkg-executor/pull/64 and https://github.com/go-vela/pkg-runtime/pull/64 for the log fixes.

**Closed** 2020-11-19 13:38 UTC
Labels: area/server, area/worker, bug, status/complete
