### ISSUE TITLE
Put the version number visibly in the UI

### ISSUE THREAD

**Issue by slushpupie** [go-vela/community#205] opened 2021-02-10 22:01 UTC
## Description

Put the version of Vela somewhere in the UI

For example, the footer on Github Enterprise includes the current release version number.

## Value

Makes it easy for users to identify which version is running, and potentially which version of documentation to look at or which features are available.

## Definition of Done

Version number is visible somewhere in the UI

## Effort  (Optional)

Likely low, but I'm only guessing.

**Comment by davidvader** [comment] 2021-02-12 16:05
this information is currently available at `GET` - `vela-server.com/version` and could easily be integrated into the UI, however it requires discussion due to lack of auth required to hit the endpoint

**Comment by susangreve** [comment] 2021-03-01 20:41
Duplicate of: #95

**Comment by cognifloyd** [comment] 2022-05-20 17:14
As noted, this is a duplicate of #95.

**Closed by cognifloyd** 2022-05-20 17:14 UTC
Labels: feature, discussion
